Introduce basic commands for controlling CoFHWorld features
CoFH/CoFHWorld pull request #2
Opened 2017-10-10 04:52 UTC by dizzyd

Introduces basic structure for adding runtime control over CoFHWorld generation. Supported commands are:

> /cofh feature - prints list of available commands
> /cofh feature list - prints list of available features which CoFHWorld is generating
> /cofh feature reload - forces a reload of the CoFHWorld configs

I'm working on the ability to dynamically generate a feature on demand in front of the user, but it will have to be a separate PR as it's a significant set of changes. :/

2017-10-10 05:07 UTC, KingLemming commented
So the only problem with this is that it completely changes the dep structure - right now, World doesn't depend on Core and that was very intentional.

World probably needs its own command, and if that just means copy/pasting how CoFHCore does it, so be it.

2017-10-10 05:35 UTC, dizzyd commented
You got it, boss. Will refactor and update.

2017-10-10 05:43 UTC, covers1624 commented
Forge now has CommandTreeBase, i recommend using that.

2017-10-10 05:50 UTC, covers1624 commented
@dizzyd Are you on the twitch chat or IRC at all by any chance?

2017-10-10 06:02 UTC, KingLemming commented
oh bleh...I guess we need to refactor CoFHCore a bit for CommandTreeBase now?

2017-10-10 12:42 UTC, dizzyd commented
@covers1624 - I'm dizzyd on esper.net.

2017-10-11 02:10 UTC, dizzyd commented
@KingLemming @covers1624 - I've refactored this PR, per your guidance and requests. Thoughts?

2017-10-11 02:34 UTC, covers1624 requested changes
Looks mostly good, Just some minor localization changes. I feel that the command is a little lacking as it doesn't provide much help to the user, Perhaps something like what i did for EnderStorage's ![commands](https://github.com/TheCBProject/EnderStorage/blob/master/src/main/java/codechicken/enderstorage/command/EnderStorageCommand.java#L27) would be nice, but its up to lemming if it should be improved more.

2017-10-11 02:34 UTC, covers1624 commented on src/main/resources/assets/cofhworld/lang/en_US.lang
> +list=Available CoFHWorld features: %s
Localizations are global, so make sure all of our stuff is prefixed like core does. That way we avoid collisions with other mods.

2017-10-11 03:51 UTC, dizzyd commented
I made all keys globally unique with prefixing.

2017-10-11 04:40 UTC, covers1624 approved these changes

2017-10-11 22:58 UTC, merged